### ISSUE TITLE
Dont Work

### ISSUE THREAD

**Issue by Staff3dx** [LimerBoy/ToxicEye#7]
I do everything according to the instructions but nothing comes to telegrams, how to fix it?

**Comment by Staff3dx** [comment]
https://i.imgur.com/wC6m7wd.png

**Comment by LimerBoy** [comment]
Напиши больше информации по ошибке.
в конфиге выставите параметры:
HideConsoleWindow на false
ProcessBSODProtectionEnabled на false

скомпилируй в Debug.

дальше откройте cmd от имени админа и через неё запустите скомпилированый файл.
и отправьте вывод коммандной строки сюда.

**Comment by Staff3dx** [comment]
![Uploading Screenshot_1.png…]()

**Comment by Staff3dx** [comment]
https://prnt.sc/s7ixtc

**Comment by Staff3dx** [comment]
[?] Sleeping 778
[+] Copying to system...
[+] Installing to autorun...
[+] Connected to internet
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org
[!] Retrying connect to api.telegram.org

**Comment by Staff3dx** [comment]
Интернет вроде нормальный оптика, почему то постоянная попытка...

**Comment by Staff3dx** [comment]
включил впн пишет 
[?] Sleeping 2974
[+] Copying to system...
[+] Installing to autorun...
[+] Connected to internet
[+] Connected to api.telegram.org
[+] Process checker started
[+] Clipper is starting...
[+] Set process critical
[!] Stopping command listener thread

**Comment by LimerBoy** [comment]
Оно не может подключиться к телеграм апи. В рашке же заблокировано вроде.

**Comment by LimerBoy** [comment]
После включения впн оно не принимает команды так как открыт диспетчер задач или другая утилити для мониторинга програм/сетевого трафика. Это что-то типо защиты от прослушки трафика. Это можно настроить в конфиге.

**Comment by Staff3dx** [comment]
Спасибо, Да я уже понял) Щас попробую нормальный впн подрублю

**Comment by Staff3dx** [comment]
Ещё вопрос криптовать можно чем-то? Не ломается

**Comment by Staff3dx** [comment]
Скажи пожалуйста, если несколько человек запустят как узнать кто из них кто?

**Comment by LimerBoy** [comment]
Под каждого человека нужно компилировать билд с новым токеном.  Тоесть делать новых ботов.

**Comment by Staff3dx** [comment]
ХМм, не удобно конечно думаю можно сделать что бы к одному боту все приходило просто было разделение между юзерами. Тип user1/user2 и тд. А так очень годный ратник спасибо

**Comment by LimerBoy** [comment]
Потом перепишу под http рат

**Comment by Staff3dx** [comment]
Привет братан, подскажи вот такая ошибка вылазит это не в твоем коде если что. Просто понять не могу в шарпе не силен. Небезопасный код вроде включил unsafe пробовал
![Screenshot_4](https://user-images.githubusercontent.com/29220432/80618766-3ee4e000-8a5d-11ea-8b00-b491e13d3eb6.png)

**Comment by Staff3dx** [comment]
Помощник по отладке управляемого кода "FatalExecutionEngineError" : "В среде выполнения обнаружена критическая ошибка. Ошибка произошла по адресу 0xba800e55 в потоке 0x1bd0. Код ошибки 0x80131623. Она может быть вызвана ошибкой в CLR или в небезопасных либо не поддающихся проверке фрагментах пользовательского кода. Обычно источниками таких ошибок бывают ошибки упаковки, допускаемые пользователями при COM-взаимодействии, либо PInvoke, повредивший стек."

**Comment by LimerBoy** [comment]
Не могу помочь, код не мой)
